### ISSUE TITLE
Could not create directory

### ISSUE THREAD

**Issue by tkawachi** [sbt-doctest/sbt-doctest#23]
It occasionally causes `Could not create directory`.

```
java.lang.RuntimeException: Could not create directory /foo/bar/target/scala-2.10/src_managed/test/com/exmpale/foo/aoaderu
        at scala.sys.package$.error(package.scala:27)
        at sbt.IO$.createDirectory(IO.scala:155)
        at sbt.OpenFile$class.open(Using.scala:45)
        at sbt.Using$$anon$2.open(Using.scala:70)
        at sbt.Using$$anon$2.open(Using.scala:70)
        at sbt.Using.apply(Using.scala:24)
        at sbt.IO$.writer(IO.scala:619)
        at sbt.IO$.write(IO.scala:615)
        at DoctestPlugin$$anonfun$1$$anonfun$apply$5$$anonfun$apply$6.apply(DoctestPlugin.scala:40)
        at DoctestPlugin$$anonfun$1$$anonfun$apply$5$$anonfun$apply$6.apply(DoctestPlugin.scala
:35)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)   
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at DoctestPlugin$$anonfun$1$$anonfun$apply$5.apply(DoctestPlugin.scala:35)
        at DoctestPlugin$$anonfun$1$$anonfun$apply$5.apply(DoctestPlugin.scala:33)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at DoctestPlugin$$anonfun$1.apply(DoctestPlugin.scala:33)
        at DoctestPlugin$$anonfun$1.apply(DoctestPlugin.scala:23)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tkawachi** [comment]
https://travis-ci.org/tkawachi/sbt-doctest/jobs/95558125#L1241

**Comment by frgomes** [comment]
I've never seen this.
